name: Generate Snake

on:
  # Schedule the workflow to run every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Define the type of runner for the job
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the snake GIF and SVG
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Chakibceran22
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build
      - name: Show git status
        run: git status

      # Push the changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Deploy the generated snake to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
